apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sonarqube
    releaseName: sonarqube
    chart: sonarqube
    valuesFile: values.yaml

generatorOptions:
  disableNameSuffixHash: true
