apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sonarqube
    version: 2025.4.0
    repo: https://SonarSource.github.io/helm-chart-sonarqube
    releaseName: sonarqube
    namespace: sonarqube
    valuesFile: values.yaml
    valuesMerge: merge
    includeCRDs: true

patchesStrategicMerge:
  - overlay/sonar-secret.yaml
