apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sonarqube
    path: ./helm-chart
    valuesFile: values.yaml
    releaseName: sonarqube

generatorOptions:
  disableNameSuffixHash: true
